### ISSUE TITLE
out = normalized*(1+gamma)+beta

### ISSUE THREAD

**Issue by Dominoer** [NVlabs/SPADE#84] opened 2019-10-14 02:05 UTC
Thanks for your code. When I try to reproduce your paper, I found that it is a little bit different between your paper and code. In your paper, you said"out = normalized * gamma + beta", where gamma and beta are learnable parameters. but in this repo, you are using "out = normalized*(1+gamma)+beta".  That confused me a lot. Could you please tell me why are you using (1+gamma) rather than gamma?

**Comment by echooooHsu** [comment] 2020-03-23 08:15
Hi, @Dominoer I have the same confusion as u, have u figure it out?

**Comment by eridgd** [comment] 2020-04-05 01:28
I would be interested to know the motivation behind this variation as well.

**Comment by ShaoTengLiu** [comment] 2020-04-30 17:11
I have the same confusion. Has anyone figured it out?

**Comment by ShaoTengLiu** [comment] 2020-05-09 05:23
I think this is similar to ResNet. Only learning the residual can be easier.

**Comment by rajatongit** [comment] 2020-08-26 11:38
May be a duplicate of #104 #4 issues. #4 contains an answer from contributors.

**Closed** 2020-08-26 11:46 UTC
